package org.junit.runners.model;

public class ClassWithATwiceInheritedDefaultTestMethod
extends ClassWithADirectlyInheritedDefaultTestMethod
implements InterfaceWithADirectlyInheritedDefaultTestMethod {

}
